export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";

export const ADD_SPRINT_SUCCESS = "ADD_SPRINT_SUCCESS";

export const GET_SPRINT_SUCCESS = "GET_SPRINT_SUCCESS";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";
