export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";

export const ADD_SPRINT_SUCCESS = "ADD_SPRINT_SUCCESS";

export const GET_SPRINT_SUCCESS = "GET_SPRINT_SUCCESS";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const GET_TASK_SUCCESS = "GET_TASK_SUCCESS";

export const DELETE_SPRINT_SUCCESS = "DELETE_SPRINT_SUCCESS";

export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";

export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
